# Generated by Django 3.1.4 on 2020-12-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=500, null=True)),
                ('img1', models.ImageField(null=True, upload_to='accessories_img')),
                ('img2', models.ImageField(null=True, upload_to='accessories_img')),
                ('img3', models.ImageField(null=True, upload_to='accessories_img')),
                ('img4', models.ImageField(null=True, upload_to='accessories_img')),
            ],
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=500, null=True)),
                ('img1', models.ImageField(null=True, upload_to='bikes_img')),
                ('img2', models.ImageField(null=True, upload_to='bikes_img')),
                ('img3', models.ImageField(null=True, upload_to='bikes_img')),
                ('img4', models.ImageField(null=True, upload_to='bikes_img')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('ticket', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Bike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_products', models.IntegerField(default=0)),
                ('bike', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.bike')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'unique_together': {('user', 'bike')},
            },
        ),
        migrations.CreateModel(
            name='Cart_Accessories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_products', models.IntegerField(default=0)),
                ('accessories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.accessories')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'unique_together': {('user', 'accessories')},
            },
        ),
        migrations.AddField(
            model_name='bike',
            name='bike',
            field=models.ManyToManyField(through='app.Cart_Bike', to='app.User'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='accessories',
            field=models.ManyToManyField(through='app.Cart_Accessories', to='app.User'),
        ),
    ]
