# Generated by Django 3.1.4 on 2020-12-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bike',
            name='size',
            field=models.CharField(choices=[('12', '12'), ('16', '16'), ('20', '20'), ('24', '24'), ('26', '26')], max_length=2, null=True),
        ),
    ]
